-- XCMG Control v6.4.0
-- Fonte oficial e sincronizada da Programação de Férias.
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.xcmg_programacao_ferias (
  id bigint generated by default as identity primary key,
  nome_chave text not null,
  nome_completo text not null,
  matricula text not null default '',
  funcao text not null default '',
  area text not null default '',
  inicio date not null,
  fim date not null,
  retorno date,
  origem text not null default 'planilha',
  atualizado_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint xcmg_programacao_ferias_datas_chk check (fim >= inicio),
  constraint xcmg_programacao_ferias_unq unique (nome_chave, inicio, fim)
);

alter table public.xcmg_programacao_ferias enable row level security;

drop policy if exists "xcmg_programacao_ferias_select" on public.xcmg_programacao_ferias;
create policy "xcmg_programacao_ferias_select"
on public.xcmg_programacao_ferias for select
to anon, authenticated
using (true);

drop policy if exists "xcmg_programacao_ferias_insert" on public.xcmg_programacao_ferias;
create policy "xcmg_programacao_ferias_insert"
on public.xcmg_programacao_ferias for insert
to anon, authenticated
with check (true);

drop policy if exists "xcmg_programacao_ferias_update" on public.xcmg_programacao_ferias;
create policy "xcmg_programacao_ferias_update"
on public.xcmg_programacao_ferias for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "xcmg_programacao_ferias_delete" on public.xcmg_programacao_ferias;
create policy "xcmg_programacao_ferias_delete"
on public.xcmg_programacao_ferias for delete
to anon, authenticated
using (true);

-- Realtime (ignora se já estiver publicado)
do $$
begin
  alter publication supabase_realtime add table public.xcmg_programacao_ferias;
exception
  when duplicate_object then null;
end $$;
