-- XCMG Control v6.10.82 — Homem × Frota
create table if not exists public.xcmg_homem_frota (
  id bigint generated by default as identity primary key,
  area text not null,
  matricula text,
  nome_completo text,
  funcao text not null,
  equipamento text not null,
  observacao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint xcmg_homem_frota_posicao_unique unique(area, funcao, equipamento)
);

alter table public.xcmg_homem_frota enable row level security;

drop policy if exists "xcmg_homem_frota_select" on public.xcmg_homem_frota;
create policy "xcmg_homem_frota_select" on public.xcmg_homem_frota for select to anon, authenticated using (true);
drop policy if exists "xcmg_homem_frota_insert" on public.xcmg_homem_frota;
create policy "xcmg_homem_frota_insert" on public.xcmg_homem_frota for insert to anon, authenticated with check (true);
drop policy if exists "xcmg_homem_frota_update" on public.xcmg_homem_frota;
create policy "xcmg_homem_frota_update" on public.xcmg_homem_frota for update to anon, authenticated using (true) with check (true);
drop policy if exists "xcmg_homem_frota_delete" on public.xcmg_homem_frota;
create policy "xcmg_homem_frota_delete" on public.xcmg_homem_frota for delete to anon, authenticated using (true);
